### ISSUE TITLE
The app Update Command failed in the terminal.

### ISSUE THREAD

**Issue by VenkateswaraT** [epicweb-dev/full-stack-foundations#100]
<img width="819" alt="image" src="https://github.com/user-attachments/assets/051567d4-af16-4293-89c0-99336bff586e">

**Comment by kentcdodds** [comment]
Sorry! The command has changed to:

```
npx update-epic-workshop
```

**Comment by kentcdodds** [comment]
Now `npx kcdshop update` will work: https://www.npmjs.com/package/kcdshop

But yeah, use `npx update-epic-workshop` instead :)

**Comment by VenkateswaraT** [comment]
Thank you for quick update
