### ISSUE TITLE
Missing "entry.client" file

### ISSUE THREAD

**Issue by jhogan97** [epicweb-dev/full-stack-foundations#103]
When attempting to hit "start app" in the first lesson, I'm met with an error stating:

Missing "entry.client" file in C:\Users\User\Documents\Full Stack Foundations\full-stack-foundations\playground\app

I can't find this file in the repo, however.

**Comment by kentcdodds** [comment]
Hmmm... Did you click "set to playground" for the exercise as described in the onboarding video? Which exercise are you on?

**Comment by jhogan97** [comment]
@kentcdodds Hi, turns out this was an issue with our VPN. Thanks!

**Comment by kentcdodds** [comment]
I'm glad you got it working!
