### ISSUE TITLE
Temporary "Unexpected Server Error" upon starting playground

### ISSUE THREAD

**Issue by xplicitone** [epicweb-dev/full-stack-foundations#11]
Clicking `START APP` from the Playground after running `npm start` yields Unexpected Server Error. It works after clicking a section on the left pane so it's not a big deal at all, but wanted to post just in case others have the issue. I can also post this in the Discord if need be.
Initial Page:
![image](https://github.com/epicweb-dev/full-stack-foundations/assets/5284515/d3efcd92-811b-4ea3-8396-83bce9f067dd)
After clicking `START APP`
![image](https://github.com/epicweb-dev/full-stack-foundations/assets/5284515/4e800ea3-b15d-4368-b844-5b28b18cc122)
After clicking Section 1: Links to Public Files
![image](https://github.com/epicweb-dev/full-stack-foundations/assets/5284515/be274ab7-b44e-4e0c-856a-453e6ae692df)

**Comment by kentcdodds** [comment]
I'm glad it works eventually. I'm unable to reproduce your issue, but I'll look for ways to make the error handling a little nicer. If you can investigate and dig up any more details that would be helpful :)

**Comment by xplicitone** [comment]
I restarted my computer and this error no longer happens, so could be cache/other tabs etc. Will close!
