### ISSUE TITLE
"Set Playground Error"

### ISSUE THREAD

**Issue by c-marc** [epicweb-dev/full-stack-foundations#2]
Hi. Sthg is not working as expected on my side.

When switching to `http://localhost:5639/01/02/problem`, I get notified (under the breadcrumb) that "Playground is not set to the right app. Click to set Playground".

When clicking, a toast shows up (bottom right) saying it failed: 

```
Set PlaygroundError
Cannot copy "../esbuild/bin/esbuild" to a subdirectory of itself "../esbuild/bin/esbuild"
```

Devtools console shows this:

![image](https://github.com/epicweb-dev/full-stack-foundations/assets/33377104/badf8eda-fef6-417c-8fed-5f9b14e8c4be)

I'm not sure what's happening and how to better report the problem, but if you've got a hint on what's failing and if you need specific details I'm happy to help.
Marc

**Comment by kentcdodds** [comment]
Hello @c-marc! Thanks for bringing this up. I think my latest commit just fixed it. I recommend starting the setup process over again.

**Comment by c-marc** [comment]
Thanks for the feedback. I just cloned the repo again and launched the setup process. It's still failing on my side but the message in the console is different:

```
Failed to load resource (....500...)     :5639/set-playground?_data=routes%2Fset-playground:1 
```

**Comment by kentcdodds** [comment]
Sorry about that. It should work now!

**Comment by c-marc** [comment]
Yes it does! Well done!
No problem. I volunteered for testing ;) Plus I can appreciate the effort you're putting in that new project. Thanks

**Comment by kentcdodds** [comment]
Thank you!
