### ISSUE TITLE
Code in currently viewed exercise does not update 

### ISSUE THREAD

**Issue by tearingItUp786** [epicweb-dev/full-stack-foundations#21]
## Description
The current exercise fails to update upon saving files. If I am viewing lesson 1.2 for example, and I update the `root.tsx` for the exercise to say `Hello world!!`, I have to utilize the dropdown and switch to an exercise and then back to the one I'm working on in the right pane for my changes to be applied.  

![CleanShot 2023-10-12 at 09 33 41@2x](https://github.com/epicweb-dev/full-stack-foundations/assets/16584942/054aa80e-8e3e-4595-8e4a-363cd735b5c6)

## Loom video
[Le Loom for context](https://www.loom.com/share/441aa48f2da44ca292dbebd1efd037c8?sid=dc201819-4526-4109-969c-061f908a2110)

**Comment by kentcdodds** [comment]
Ah, the reason is you're changing code in the `exercises` directory. You should be working in the `playground` directory only.

I'm going to be making a video showing how to use the workshop app today, but this is described briefly in: https://www.epicweb.dev/get-started

Thanks!
