### ISSUE TITLE
Error when typing "npm start" for the first time

### ISSUE THREAD

**Issue by chaiwat-pand** [epicweb-dev/full-stack-foundations#28]
Unfortunately I am unable to run the local app on my computer. After typing "npm start" in the terminal, I get a bunch of errors.

Error message: 
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at userAgentContains (file:///Users/chaiwatpandey/Desktop/full-stack-foundations/node_modules/@kentcdodds/workshop-app/node_modules/framer-motion/dist/es/projection/node/create-projection-node.mjs:1470:25)
    at file:///Users/chaiwatpandey/Desktop/full-stack-foundations/node_modules/@kentcdodds/workshop-app/node_modules/framer-motion/dist/es/projection/node/create-projection-node.mjs:1476:20
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async file:///Users/chaiwatpandey/Desktop/full-stack-foundations/node_modules/@kentcdodds/workshop-app/start.js:31:2
Encountered error running the server, exiting...

Image:
<img width="1040" alt="image" src="https://github.com/epicweb-dev/full-stack-foundations/assets/98444718/17309fd6-fc72-4ea4-a9b7-17b8fca6f0d9">

**Comment by kei95** [comment]
For whoever having the same problem, that's likely because your node js version is 21.0.0. Bump up to the latest version should resolve it.

reference: https://www.framer.community/c/bugs/node-21-typeerror-cannot-read-properties-of-undefined-reading-tolowercase

**Comment by chaiwat-pand** [comment]
I am currently using Node.js version 19.0.0 and it works fine too.
