### ISSUE TITLE
Videos are not loading

### ISSUE THREAD

**Issue by intanta** [epicweb-dev/full-stack-foundations#50]
None of the videos are loading in Workshop app, instead the error is being displayed: "Sorry, failed loading videos. Check the terminal output?"

The setup was successful, no issues. Running `npm start` also does not produce any console errors:
<img width="349" alt="image" src="https://github.com/epicweb-dev/full-stack-foundations/assets/13807249/133d75ca-2cb7-43ac-9542-41a158b794b7">

In browser console I see this:
<img width="577" alt="image" src="https://github.com/epicweb-dev/full-stack-foundations/assets/13807249/9609160f-45d4-4993-8e40-285d758924bb">

Tried Chrome, Safari and Firefox - same result

**Comment by kentcdodds** [comment]
I've just pushed an update that should log out the error for when loading a video fails. Could you run `npx kcdshop update` to get the latest version of the workshop and try again? If it doesn't work, you should get logs, please share them with me here.

**Comment by intanta** [comment]
The update fixed it, videos are loading now. Thank you
