### ISSUE TITLE
After successful setup, tests fail because browsers are not installed

### ISSUE THREAD

**Issue by gregdeane** [epicweb-dev/full-stack-foundations#51]
Not sure if either of the issues below are actual bugs or if I've just missed mention of them in the documentation. Apologies if so!

### Note the successful setup and server start

<img width="710" alt="Screenshot 2023-10-28 at 13 22 41" src="https://github.com/epicweb-dev/full-stack-foundations/assets/4949000/aa611847-d734-452f-8819-292932c2dce1">

### Note the test failure:

<img width="528" alt="Screenshot 2023-10-28 at 13 22 59" src="https://github.com/epicweb-dev/full-stack-foundations/assets/4949000/d229dcb0-c73f-45b6-844a-13ddcb85a6d8">

Running the `npx playwright install` command as instructed solves the issue.

## Playwright `show-report` not working.
`npx playwright show-report` fails. Note: I ran this command after fixing tests as mentioned above and running the tests successfully.

<img width="574" alt="Screenshot 2023-10-28 at 13 23 29" src="https://github.com/epicweb-dev/full-stack-foundations/assets/4949000/7e9cefa8-276a-477d-a2aa-41f7769c908c">

**Comment by kentcdodds** [comment]
Hi @gregdeane,

Thanks for reporting this. I've fixed the installation issue. To see the report, you'll have to run `npx playwright show-report` from within the `playground` directory where the test has been run.
