### ISSUE TITLE
[07. Error Handling / 03. Error Bubbling] `GeneralErrorBoundary` component style

### ISSUE THREAD

**Issue by lytovka** [epicweb-dev/full-stack-foundations#58]
Hey Kent! Thanks for your tremendous work on EpicWeb workshops.

I have one – a rather subjective – piece of feedback regarding the [`app/components/error-boundary.tsx`](https://github.com/epicweb-dev/full-stack-foundations/blob/main/exercises/07.error-handling/03.problem.error-bubbling/app/components/error-boundary.tsx) component. When I first read the code, I was a bit thrown off. Would it improve readability to reorganize the types and default values so that they are not nested within the `GeneralErrorBoundary`? I'm alluding to something like this:

<details>
<summary>error-boundary.tsx</summary>

```tsx
import {
  isRouteErrorResponse,
  useParams,
  useRouteError,
} from '@remix-run/react'
import { type ErrorResponse } from '@remix-run/router'
import { getErrorMessage } from '#app/utils/misc.tsx'

type StatusHandler = (info: {
	error: ErrorResponse
	params: Record<string, string | undefined>
}) => JSX.Element | null

type GeneralErrorBoundaryProps = {
	defaultStatusHandler?: StatusHandler
	statusHandlers?: Record<number, StatusHandler>
	unexpectedErrorHandler?: (error: unknown) => JSX.Element | null
}

const DefaultStatusHandler: StatusHandler = ({ error }) => <p>{error.status} {error.data}</p>

export function GeneralErrorBoundary({
  defaultStatusHandler = DefaultStatusHandler,
  statusHandlers,
  unexpectedErrorHandler = error => <p>{getErrorMessage(error)}</p>,
}: GeneralErrorBoundaryProps) {
  const error = useRouteError()
  const params = useParams()

	if (typeof document !== 'undefined') {
		console.error(error)
	}

	return (
		<div className="container mx-auto flex h-full w-full items-center justify-center bg-destructive p-20 text-h2 text-destructive-foreground">
			{isRouteErrorResponse(error)
				? (statusHandlers?.[error.status] ?? defaultStatusHandler)({
						error,
						params,
				  })
				: unexpectedErrorHandler(error)}
		</div>
	)
}

```
</details>

Usually, I don't nitpick code style in open-source projects, and in the grand scheme of things, it's a pretty minor nuance. However, because this is educational content, I thought it was worth mentioning. Thanks!

**Comment by kentcdodds** [comment]
Thanks for the feedback. This is pretty subjective and I like the way it is now so I'm not going to change it. But you're welcome to do so in your own projects. Thanks!
