### ISSUE TITLE
04. DATA MUTATIONS/05. INTENT (💪 PROBLEM)

### ISSUE THREAD

**Issue by boringtutor** [epicweb-dev/full-stack-foundations#60]
i was just solving the 04. DATA MUTATIONS/05. INTENT (💪 PROBLEM)
and i just noticed that on the home page in file root.tsx ,in link the path is hard coded .But there is a problem with that when we delete the first note and when we go back to the home page and try to click on the link to go to kody notes it throws the error "404 NOT FOUND" .if we just  change
```js
<Link className="underline" to="users/kody/notes/d27a197e">  to
<Link className="underline" to="users/kody/notes">

**Comment by kentcdodds** [comment]
Thanks! I've fixed this 👍
