### ISSUE TITLE
07-02 Not sure what this code block is trying to illustrate

### ISSUE THREAD

**Issue by mattsears18** [epicweb-dev/full-stack-foundations#62]
I'm not sure what this particular code block is trying to illustrate. Maybe the add/remove diff colors are on the wrong lines?

https://github.com/epicweb-dev/full-stack-foundations/blob/9724781cbcdc8944563e84ea0b548fa5daf9d888/exercises/07.error-handling/02.problem.thrown-response/README.mdx#L115-L139

<img width="766" alt="Screenshot 2023-11-06 at 8 36 05 AM" src="https://github.com/epicweb-dev/full-stack-foundations/assets/5251446/622a1a85-d280-42c4-9939-1966f3af209d">

**Comment by kentcdodds** [comment]
Yikes! You're right. I have no idea what went wrong there 😅 Fixed it!

<img width="827" alt="image" src="https://github.com/epicweb-dev/full-stack-foundations/assets/1500684/8e369c0f-b9c1-4ffc-9dd8-53d7ad72179b">

**Comment by mattsears18** [comment]
That makes much more sense now. Haha, thanks!

**Comment by kentcdodds** [comment]
I actually messed it up again. Now it's better 😅

<img width="827" alt="image" src="https://github.com/epicweb-dev/full-stack-foundations/assets/1500684/0ec8d68e-2b49-47de-9789-42d6367d4ede">
