### ISSUE TITLE
Getting error while setting up the workshop

### ISSUE THREAD

**Issue by saurabhp75** [epicweb-dev/full-stack-foundations#64]
I am getting following error while setting up the workshop repo for full-stack-foundations.
OS: MacOS 14
Git version: 2.42.1
Node version: v19.8.1
Npm version: 9.5.1

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@kentcdodds/workshop-app@2.56.3',
npm WARN EBADENGINE   required: { node: '18' },
npm WARN EBADENGINE   current: { node: 'v19.8.1', npm: '9.5.1' }
npm WARN EBADENGINE }

**Comment by kentcdodds** [comment]
Thanks for reporting!

I recommend you get off of odd-versions of Node.js (learn more): https://nodejs.org/en/about/previous-releases

I'm pushing a fix for this soon. Cheers!
