### ISSUE TITLE
npm test returns error sh: playwrite: command not found

### ISSUE THREAD

**Issue by nac62116** [epicweb-dev/full-stack-foundations#7]
Hey there, i got everything set up for the workshop next week and i'm very exited.

But when i want to run the tests via "npm test" it throws following error:

![grafik](https://github.com/epicweb-dev/full-stack-foundations/assets/56918308/5db8f208-5797-4d95-b8f9-acc2f9c1527f)

Shouldn't the command be "playwright" instead of "playwrite"? Or do i need to install playwrite via npm (globally)?

**Comment by kentcdodds** [comment]
You're right 🤦‍♂️ Thanks for checking on that. That's been fixed.
