### ISSUE TITLE
Support for Node 18.19 with NPM 10 bundled in lts/hydrogen release Nov. 29, 2023

### ISSUE THREAD

**Issue by Twintails** [epicweb-dev/full-stack-foundations#71]
Node 18.19 dropped last week with NPM 10 bundled.

current:
when attempting to run `npm start` while based in Node 18.19 engine env an Error is reported 
Ref Image:
<img width="1064" alt="terminal of node internal process esm loader ERROR" src="https://github.com/epicweb-dev/full-stack-foundations/assets/4665314/cba64721-3dc8-43eb-8316-6d49b0d128ff">

NPM 10, it seems, is errantly reporting a deprecation incoming for Node 20.6 regarding --loader flag on commands

Expected:
App launches like it would in Node < 18.19 as per run reqs.

**Comment by kevinbailey25** [comment]
Got this error as well. 

But if you downgrade node to version 18.18.2 it works

**Comment by kentcdodds** [comment]
This should be fixed. Cheers!
