### ISSUE TITLE
issue While npm run setup : ✘ [ERROR] Cannot process MDX file with esbuild [plugin @mdx-js/esbuild]

### ISSUE THREAD

**Issue by srujana-e** [epicweb-dev/full-stack-foundations#78]
full-stack-foundations/exercises/07.error-handling/03.solution.error-bubbling/README.mdx Error: Build failed with 1 error:
README.mdx:0:0: ERROR: [plugin: @mdx-js/esbuild] Cannot process MDX file with esbuild

**Comment by kentcdodds** [comment]
Hi @srujana-e!

I'm afraid I don't know what could be causing this issue for you. I just tried the setup myself and it seems to be working for me and the last changes to the repo are running successfully in CI as well (which runs on Linux, MacOS, and Windows). Could you try again and let me know if it works for you?
