### ISSUE TITLE
App don't Start

### ISSUE THREAD

**Issue by knupel** [epicweb-dev/full-stack-foundations#86]
Hello,

I begin the first exercise of "Full Stack Foundation" every thing is well until I try to launch the App in local environment 
`http://localhost:5639/01/01/problem`
when I start it nothing happen and the message on the window is 
<img width="700" alt="Capture d’écran 2024-02-27 à 18 39 39" src="https://github.com/epicweb-dev/full-stack-foundations/assets/3332269/80691001-bb65-451e-894a-3450bba149cb">
 and the console in VS code display
```
[playground:4000] > dev
[playground:4000] > remix dev --manual -c "node ./server/dev-server.js"
[playground:4000] 
[playground:4000] 
[playground:4000] 
[playground:4000]  💿  remix dev
[playground:4000] 
[playground:4000] 
[playground:4000] [info] building...
[playground:4000] 
[playground:4000] ✘ [ERROR] Could not resolve "@kentcdodds/workshop-app/iframe-sync"
[playground:4000] 
[playground:4000]     app/kcdshop.tsx:23:34:
[playground:4000]       23 │ ...{ KCDShopIFrameSync } from '@kentcdodds/workshop-app/iframe-sync';
[playground:4000]          ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[playground:4000] 
[playground:4000]   The path "./iframe-sync" is not exported by package "@kentcdodds/workshop-app":
[playground:4000] 
[playground:4000]     ../node_modules/@kentcdodds/workshop-app/package.json:21:13:
[playground:4000]       21 │   "exports": {
[playground:4000]          ╵              ^
[playground:4000] 
[playground:4000]   You can mark the path "@kentcdodds/workshop-app/iframe-sync" as external to exclude it from the bundle, which will remove this error.
[playground:4000] 
```

I don't understand what I can do and where I can find help to solve it.

**Comment by kentcdodds** [comment]
Looks like you've got an old version of the workshop material and a new version of the workshop app. There was a breaking change so you'll need to update. Do this:

```
npx kcdshop update
```

Then delete the playground directory with the outdated code `rm -rf ./playground` and you should be set!

Let me know if this doesn't work for you!

**Comment by knupel** [comment]
thx for your quick answer.
I find now the solution. I make again `npm run setup`and know that's work fine :)
