### ISSUE TITLE
Failed setup on arch linux

### ISSUE THREAD

**Issue by swarajspatil158** [epicweb-dev/full-stack-foundations#88]
![image](https://github.com/epicweb-dev/full-stack-foundations/assets/67370080/df2ba4bb-412f-478e-afd7-774a2c4007da)

Logs:
Run `npm audit` for details.
    ✅  Success: Dependency Installation

    ▶️   Starting: Custom Setup
          Handling custom setup (if neccessary)
          Running the following command: npm run setup:custom --if-present

> setup:custom
> node ./scripts/setup-custom.js

🛝  setting up the first problem app...
✅ first problem app set up
🎭 installing playwright for testing... This may require sudo (or admin) privileges and may ask for your password.
BEWARE: your OS is not officially supported by Playwright; installing dependencies for ubuntu20.04-x64 as a fallback.
Installing dependencies...
Switching to root user to install dependencies...
sh: line 1: apt-get: command not found
Failed to install browsers
Error: Installation process exited with code: 127
    🚨  Failure: Custom Setup. Please review the messages above for information on how to troubleshoot and resolve this issue.

**Comment by kentcdodds** [comment]
I think you need to install apt-get and make sure it's available on your PATH.
