### ISSUE TITLE
NPM version out of date. 

### ISSUE THREAD

**Issue by salymk** [epicweb-dev/full-stack-foundations#92]
I'm using fnm to manage my node versions, I have the latest version of node and npm, but it keeps saying that I have an out of date version of npm.

![image](https://github.com/epicweb-dev/full-stack-foundations/assets/21187230/e64f0ce8-1b0d-49af-a77d-a9986e2cefa2)

**Comment by kentcdodds** [comment]
If you're sure your system is good, then you can manually set up with:

```
npm install
npm run setup:custom
```

I hope that helps!

**Comment by salymk** [comment]
I had a local install of Nodejs on my desktop, which caused my issues. After deleting it, everything installed correctly.

**Comment by kentcdodds** [comment]
I'm glad you worked it out!

**Comment by salymk** [comment]
Thank you Kent, your suggestion helped me find the problem.
